stages:
  - check           # check that requirements are met before starting the deployement
  - deploy

image: "${CI_REGISTRY}/bioinfo-containers/deploy-geniac:devel"

cache:
  paths:
    - vendor/python


before_script:
  - set -euo pipefail
  - source /opt/etc/bashrc # needed to activate the geniac conda env


docs:
  stage: check
  script:
    - conda env create -f docs/environment.yml
    - conda activate readthedocs
    - cd docs
    - python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
    - mv _build/html $CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


pytest:
  stage: check
  script:
    - pytest

pypi:
  stage: deploy
  script:
    - env
    - python -m pip install --upgrade build twine
    - python -m build
    - ls dist/*
    - TWINE_PASSWORD=${PYPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
  only:
    - tags

