set(CMAKE_INSTALL_PREFIX "$HOME/local" CACHE PATH "Install path prefix, prepended onto install directories.")
set(ap_annotation_path "" CACHE STRING "Path to the annotations. If the variable ap_use_annotation_link is ON, a symlink annotation with the given target will be created.")
set(ap_install_docker_images "OFF" CACHE BOOL "Generate and install Dockerfiles and images")
set(ap_install_docker_recipes "OFF" CACHE BOOL "Generate and install Dockerfiles")
set(ap_install_singularity_images "OFF" CACHE BOOL "Generate and install Singularity def files and images")
set(ap_install_singularity_recipes "OFF" CACHE BOOL "Generate and install singularity def files")
set(ap_nf_executor "pbs" CACHE STRING "executor used by nextflow (e.g. pbs, slurm, etc.)")
set(ap_singularity_image_path "" CACHE STRING "Path to the singularity images. If the variable ap_use_singularity_image_link is ON, a symlink containers/singularity with the given target will be created.")
