set(CMAKE_INSTALL_PREFIX "/bioinfo/local/curie/ngs-data-analysis/centos/RNA-seq" CACHE PATH "")
set(ap_annotation_path "/data/annotations/pipelines" CACHE PATH "")
set(ap_nf_executor "pbs" CACHE STRING "")
set(ap_singularity_image_path "/bioinfo/local/curie/ngs-data-analysis/centos/tools/containers/singularity/rnaseq-2.0/images" CACHE PATH "")
set(ap_tools_path "/to/replace if ap_use_toolspath is ON" CACHE PATH "")
set(ap_use_containers "ON" CACHE BOOL "")
set(ap_use_toolspath "OFF" CACHE BOOL "")
