# -*- coding: utf-8 -*-
#
# geniac documentation build configuration file, created by
# sphinx-quickstart on Sat Dec 14 00:00:42 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

import re

extensions = ['sphinx.ext.mathjax', 'sphinx_mdinclude',
    'sphinx.ext.githubpages']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'geniac'
copyright = u'2019-2025, Institut Curie'
author = u'Philippe Hupé'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = re.sub('^version-', '', os.popen('git describe').read().strip())
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '*.inc.rst', 'README.md']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_logo = 'images/geniac-logo.svg'
html_favicon = 'images/geniac-logo.png'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'geniacdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'geniac.tex', u'geniac Documentation',
     u'Philippe Hupé', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'geniac', u'geniac Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'geniac', u'geniac Documentation',
     author, 'Philippe Hupé', 'Automatic Configuration GENerator and Installer for nextflow pipelines.',
     'Miscellaneous'),
]


# -- Below is a custom Geniac function --------------------------------------

# it provide the mdinclude_offset command to include markdown file
# and shift the heading by an offset
# usage:
# 
#     .. mdinclude:: path/markdown/file.md
#        :offset: 2

from sphinx_mdinclude.sphinx import MdInclude
from docutils.parsers.rst.directives import unchanged
import tempfile

class MdIncludeWithOffset(MdInclude):
    option_spec = MdInclude.option_spec.copy()
    option_spec['offset'] = unchanged  # Add the offset option

    def run(self):
        offset = int(self.options.get('offset', 0))
        md_file = self.arguments[0]

        # Read the Markdown file
        with open(md_file, 'r') as f:
            content = f.readlines()

        # Apply the offset to headings
        if offset > 0:
            new_content = []
            for line in content:
                if line.lstrip().startswith('#'):
                    # Increase heading level by `offset`
                    new_line = line[:line.index('#')] + '#' * offset + line[line.index('#'):]
                    new_content.append(new_line)
                else:
                    new_content.append(line)
            content = new_content

        # Convert the content to a string
        modified_content = ''.join(content)

        # Write the modified content to a temporary file in /tmp
        temp_file_path = '/tmp/modified_content.md'
        with open(temp_file_path, 'w') as temp_file:
            temp_file.write(modified_content)

        try:
            # Override the arguments to use the temporary file
            self.arguments[0] = temp_file_path

            # Call the parent class's run method
            return super().run()
        finally:
            # Optionally, you can choose not to clean up the file if you want to inspect it later
            pass  # os.unlink(temp_file_path)

def setup(app: Sphix):
    app.add_directive('mdinclude_offset', MdIncludeWithOffset)
    return {'version': '1.0', 'parallel_read_safe': True}
